### ISSUE TITLE
Reduce the size of screenshots

### ISSUE THREAD

**Issue by UgaitzEtxebarria** [UgaitzEtxebarria/jellyfin-tizen#11]
The screenshots images must be less or equal than 500kB, maintaining the resolution of 1920 X 1080 and 24bit

Web need to reduce the size of this images:

 * screenshot_jellyfin01.png
 * screenshot_jellyfin03.png
 * screenshot_jellyfin04.png
 * screenshot_jellyfin05.png

**Comment by J-C-B** [comment]
Done - PR awaits

**Comment by J-C-B** [comment]
Changed to JPG from PNG - can be closed

**Comment by UgaitzEtxebarria** [comment]
Closed
